name: Release Patch

on: workflow_dispatch

jobs:
  release-patch:
    name: Release Patch
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Set patch version
        id: patch_version
        run: |
          PATCH_VERSION=v$(npm version | grep 'aria2-integration' | grep -oP "\d+\.\d+.\d+")
          SHORT_SHA=$(git rev-parse --short HEAD)
          node scripts/update-version.js $PATCH_VERSION $SHORT_SHA
          npm install
          npm run lint:fix
          echo "PATCH_VERSION=$PATCH_VERSION" >> $GITHUB_OUTPUT
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
      - name: Commit, push and create tag
        uses: EndBug/add-and-commit@v9
        with:
          fetch: true
          default_author: github_actions
          message: Release ${{ steps.patch_version.outputs.PATCH_VERSION }} (${{ steps.patch_version.outputs.SHORT_SHA }})
          pathspec_error_handling: exitImmediately
          push: true
          tag: ${{ steps.patch_version.outputs.PATCH_VERSION }}
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ steps.patch_version.outputs.PATCH_VERSION }} --generate-notes
      - name: Set next dev version
        id: dev_version
        run: |
          DEV_VERSION=$(npm version --no-git-tag-version --no-commit-hooks patch)
          SHORT_SHA=$(git rev-parse --short HEAD)
          node scripts/update-version.js $DEV_VERSION $SHORT_SHA
          npm install
          npm run lint:fix
          echo "DEV_VERSION=$DEV_VERSION" >> $GITHUB_OUTPUT
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          fetch: true
          default_author: github_actions
          message: Set next dev version to ${{ steps.dev_version.outputs.DEV_VERSION }} (${{ steps.dev_version.outputs.SHORT_SHA }})
          pathspec_error_handling: exitImmediately
          push: true
